### ISSUE TITLE
Servo's not working(Not using Bluetooth)

### ISSUE THREAD

**Issue by Flee-Time** [kasinatorhh/BTSpidey#1]
first off all thank you for this great project , like i said servos are doing nothing with the firmware being uploaded , tried the serial port and still nothing , using an arduino nano (clone) , 13 sg90 servos wich i will switch to mg90s and a pca9685 driver (clone) , i would be very greatfull if you could look into this and i know that the driver cards adress is 0x40 becouse other quadrupled firmwares move the servos.

**Comment by kasinatorhh** [comment]
Unfortunately the bring up is not explained. You observed a protection mechanism.
Com parameters: when using USB, baudrate should be 115200 baud. If bluetooth is not working as expected, use format bluetooth command (if I remember correct,  Q or q)
The servos should move when using e.g. the "g 1 300" command. Note: a zero is coded as "g 0. 300"
Check each servo one after to be able to move full scale. Use values between 100 and 550. Go back to a non hitting value to save current and prevent from overheating. Adjust the mounting position that you can use the full mechanical range.

By that you should move the servos to the position as shown on my pictures. That is 0 degrees on all axes.
Save the 0 position by using the r 1 300 command.
Move legs (coxa) front 90°, save by R 1 500 command (use always you values)
Thibia 90° is when moving down.
Femur is 90° when its farthest spread out.
Move there servos further until either they hit the body, or don't move any more. Save the lower value by using N 1 100 and the upper value by M 1 500.
Saving only works when you unprotected eeprom writes, by sending UNPROTECT to the spider.
Once the min, max 0 and 90° values are set, the servos should also move using the G 1 0 command or the regular moves.
Once the servos are calibrated, protect EEPROM  by sending PROTECT. I installed that protection, because sometimes communication provides biterrors, that might change calibration, then one or the other lag is not moving. 
I see that I should maybe append a step by step bring up guide here, correct?

**Comment by Flee-Time** [comment]
I am not using a bluetooth chip with my spider , if that will be a problem how can i edit the code so it doesn't need a bluetooth serial interface, im currently at work so i will try these when im home , thank you for the help, and yeah a step by step guide will help people like me.

**Comment by kasinatorhh** [comment]
Bluetooth is explicitly optional. If no input is provided, fine...
Let me check how the guide can work on Github-Wiki

**Comment by kasinatorhh** [comment]
Have a look here:
https://github.com/kasinatorhh/BTSpidey/wiki/Step-by-Step-first-time-bring-up

**Comment by Flee-Time** [comment]
The servo's are working thank you , another question 2 of the servos are inverted how can i invert the servo rotation ?

**Comment by kasinatorhh** [comment]
Normally this is covered by using the right R/r codes. 
It shows 0° and 90°.
Please check whether the reported values really move there

**Comment by kasinatorhh** [comment]
R <servoid> <Value> Sets the 90° Angle,
r <servoid> <Value> Sets the 0° Angle ad shown on the instruction page

**Comment by kasinatorhh** [comment]
According to the information servo do not move, the issue is closed. 
If you have other remarks, please open new issue. Makes it easier for others to find things. 
Please post a make:)
